from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('pepito/', admin.site.urls),
    path("harrys/", views.harrys),
    path("harrysSerializer/", views.harrysSerializer),
    path("restfull/region/", views.harrys),
    path("region/<int:cod_region>", views.rf_region_reg),
    path("region", views.rf_region),
    path("contacto", views.rf_contacto),
    path("calidadtour/<int:id_contacto>", views.rf_contacto_reg),
    path("calidadtour", views.rf_calidadtour),
    path("calidadtour/<int:id_calidad>", views.rf_calidadtour_reg),
    path("categoriaeva", views.rf_categoriaeva),
    path("categoriaeva/<int:id_cat_eva>", views.rf_categoriaeva_reg),
    path("estado", views.rf_estado),
    path("estado/<int:id_estado>", views.rf_estado_reg),
    path("factura", views.rf_factura),
    path("factura/<int:id_factura>", views.rf_factura_reg),
    path("genero", views.rf_genero),
    path("genero/<int:id_genero>", views.rf_genero_reg),
    path("idioma", views.rf_idioma),
    path("idioma/<int:id_idioma>", views.rf_idioma_reg),
    path("pais", views.rf_pais),
    path("pais/<int:id_pais>", views.rf_pais_reg),
    path("rrss", views.rf_rrss),
    path("rrss/<int:id_rrss>", views.rf_rrss_reg),
    path("tipoempresa", views.rf_tipoempresa),
    path("tipoempresa/<int:id_tipo_empr>", views.rf_tipoempresa_reg),
    path("tipoguia", views.rf_tipoguia),
    path("tipoguia/<int:id_tip_guia>", views.rf_tipoguia_reg),
    path("ciudad", views.rf_ciudad),
    path("ciudad/<int:id_ciudad>", views.rf_ciudad_reg),
    path("cliente", views.rf_cliente),
    path("cliente/<int:id_cliente>", views.rf_cliente_reg),
    path("empresa", views.rf_empresa),
    path("empresa/<int:id_empresa>", views.rf_empresa_reg),
    path("evaluacion", views.rf_evaluacion),
    path("evaluacion/<int:id_eva_tour>", views.rf_evaluacion_reg),
    path("pasajerocontacto", views.rf_pasajerocontacto),
    path("pasajerocontacto/<int:id_pasaj>", views.rf_pasajerocontacto_reg),
    path("tour", views.rf_tour),
    path("tour/<int:id_tour>", views.rf_tour_reg),
    path("turnotrabajo", views.rf_turnotrabajo),
    path("turnotrabajo/<int:id_turno>", views.rf_turnotrabajo_reg),
    path("horario", views.rf_horario),
    path("horario/<int:id_horario>", views.rf_horario_reg),
    path("itinerario", views.rf_itinerario),
    path("itinerario/<int:id_itinerario>", views.rf_itinerario_reg),
    path("reserva", views.rf_reserva),
    path("reserva/<int:id_reserva>", views.rf_reserva_reg),
    #path("detallereserva", views.rf_detallereserva),
    #path("detallereserva/<int:id_det_reserva>", views.rf_detallereserva_reg),
    #path("detallefactura", views.rf_detallefactura),
    #path("detallefactura/<int:id_det_fac>", views.rf_detallefactura_reg),
    #path("detalletour", views.rf_detalletour),
    #path("detalletour/<int:id_det_tour>", views.rf_detalletour_reg),
    path("guia", views.rf_guia),
    path("guia/<int:id_guia>", views.rf_guia_reg),
    #path("detalleguia", views.rf_detalleguia),
    #path("detalleguia/<int:id_det_guia>", views.rf_detalleguia_reg),
    path("usuario", views.rf_usuario),
    path("usario/<int:id_usuario>", views.rf_usuario_reg),
]
