# Generated by Django 4.1.7 on 2023-06-22 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('nom_ciu', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ciudad',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=20)),
                ('ape_pat', models.CharField(db_column='ap_pat', max_length=20)),
                ('ape_mat', models.CharField(db_column='ap_mat', max_length=20)),
                ('genero', models.CharField(max_length=10)),
                ('contacto', models.CharField(max_length=30)),
                ('direccion', models.TextField(default=0)),
                ('email', models.EmailField(max_length=50)),
                ('id_ciudad', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administrador.ciudad')),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('nom_contacto', models.CharField(max_length=30)),
                ('ape_contacto', models.CharField(max_length=30)),
                ('email_contacto', models.EmailField(max_length=50)),
                ('fono_contacto', models.IntegerField(null=True)),
                ('mensaje', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'contacto',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('des_estado', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'estado',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=10)),
                ('porc_factura', models.IntegerField(null=True)),
                ('porc_iva', models.IntegerField(null=True)),
                ('monto_iva', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'factura',
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id_idioma', models.AutoField(primary_key=True, serialize=False)),
                ('des_idioma', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'idioma',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('nom_pais', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pais',
            },
        ),
        migrations.CreateModel(
            name='PasajeroContacto',
            fields=[
                ('id_pasaj', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=10)),
                ('nom_pasaj', models.CharField(max_length=20)),
                ('ap_pasaj', models.CharField(db_column='apellidos', max_length=30)),
                ('fono', models.IntegerField(null=True)),
                ('email_pasaj', models.EmailField(max_length=50)),
                ('ciudad', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'pasajero_contacto',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id_tour', models.AutoField(primary_key=True, serialize=False)),
                ('nom_tour', models.CharField(max_length=20)),
                ('fecha_tour', models.CharField(max_length=10)),
                ('desc_tour', models.TextField(default=0)),
                ('valor_tour', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'tour',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=30)),
                ('clave', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='TurnoTrabajo',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('desc_horario', models.CharField(max_length=20)),
                ('tramo_ini', models.CharField(max_length=5)),
                ('tramo_fin', models.CharField(max_length=5)),
                ('id_estado', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administrador.estado')),
            ],
            options={
                'db_table': 'turno_trabajo',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('cant_nino', models.IntegerField(null=True)),
                ('cant_adulto', models.IntegerField()),
                ('tot_cant', models.IntegerField()),
                ('id_pasaj', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administrador.pasajerocontacto')),
                ('id_tour', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administrador.tour')),
            ],
            options={
                'db_table': 'reserva',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('hora', models.CharField(max_length=15)),
                ('duracion', models.IntegerField(null=True)),
                ('modo', models.CharField(max_length=100)),
                ('id_estado', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administrador.estado')),
            ],
            options={
                'db_table': 'horario',
            },
        ),
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id_guia', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=10)),
                ('nom_guia', models.CharField(max_length=20)),
                ('pape_guia', models.CharField(db_column='ap_pat', max_length=20)),
                ('sape_guia', models.CharField(db_column='ap_mat', max_length=20)),
                ('contacto_guia', models.CharField(max_length=30)),
                ('fnac_guia', models.CharField(max_length=10)),
                ('email_guia', models.EmailField(max_length=50)),
                ('id_pais', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administrador.pais')),
            ],
            options={
                'db_table': 'guia',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nom_empresa', models.CharField(max_length=20)),
                ('rut_empr', models.CharField(max_length=10)),
                ('email_empr', models.EmailField(max_length=50)),
                ('contacto_empr', models.CharField(max_length=30)),
                ('direccion_empr', models.TextField(default=0)),
                ('representante', models.CharField(max_length=30)),
                ('nom_dueño', models.CharField(max_length=20)),
                ('rut_dueño', models.CharField(max_length=10)),
                ('contacto_dueño', models.CharField(max_length=30)),
                ('email_dueño', models.EmailField(max_length=50)),
                ('id_ciudad', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administrador.ciudad')),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='DetalleTour',
            fields=[
                ('id_det_tour', models.AutoField(primary_key=True, serialize=False)),
                ('id_ciudad', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_ciudad', to='administrador.ciudad')),
                ('id_guia', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_guia', to='administrador.guia')),
                ('id_horario', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administrador.horario')),
                ('id_tour', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administrador.tour')),
            ],
            options={
                'db_table': 'detalle_tour',
            },
        ),
        migrations.CreateModel(
            name='DetalleReserva',
            fields=[
                ('id_det_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('monto_reserva', models.IntegerField(null=True)),
                ('id_ciudad', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administrador.ciudad')),
                ('id_cliente', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administrador.cliente')),
                ('id_estado', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administrador.estado')),
                ('id_reserva', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administrador.reserva')),
            ],
            options={
                'db_table': 'detalle_reserva',
            },
        ),
        migrations.CreateModel(
            name='DetalleGuia',
            fields=[
                ('id_det_guia', models.AutoField(primary_key=True, serialize=False)),
                ('nom_horario_guia', models.CharField(max_length=100)),
                ('id_guia', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administrador.guia')),
                ('id_idioma', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administrador.idioma')),
            ],
            options={
                'db_table': 'detalle_guia',
            },
        ),
        migrations.CreateModel(
            name='DetalleFac',
            fields=[
                ('id_det_fac', models.AutoField(primary_key=True, serialize=False)),
                ('fech_fac', models.DateTimeField(auto_now_add=True)),
                ('tot_fac', models.IntegerField(null=True)),
                ('id_det_reserva', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administrador.detallereserva')),
                ('id_factura', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administrador.factura')),
            ],
            options={
                'db_table': 'detalle_fac',
            },
        ),
        migrations.AddField(
            model_name='ciudad',
            name='id_pais',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administrador.pais'),
        ),
    ]
